# Generated by Django 2.1.3 on 2019-05-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='listimg',
            field=models.ImageField(blank=True, default='normal.png', upload_to='list', verbose_name='列表页图'),
        ),
    ]
