# Generated by Django 2.1.3 on 2019-05-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0003_auto_20190517_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='listimg',
            field=models.ImageField(default='normal.png', upload_to='list', verbose_name='列表页图'),
        ),
    ]
