# Generated by Django 2.1.3 on 2019-05-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_bank_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banklist',
            name='bankimg',
            field=models.ImageField(default='', upload_to='banklist', verbose_name='logo'),
        ),
    ]
